[tool.black]
line-length = 100
target-version = ["py311"]

[tool.codespell]
ignore-regex = "\\[nt]" # Do not count escaped newlines or tabs as part of a word
# ignore-words-list = ""
quiet-level = 0 # Display all warnings
check-filenames = ""
check-hidden = ""

[tool.isort]
py_version = "311"
line_length = 100
atomic = true
combine_as_imports = true
force_sort_within_sections = true
profile = "black"

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
python_version = "3.11"
strict = true
warn_unreachable = true

[tool.pydocstyle]
convention = "google"

[tool.pylint.format]
# Let Black handle line length
max-line-length = 300

[tool.pylint.messages_control]
# Most of these are disabled to prevent issues with dependencies being difficult to inspect
# pylint FAQ recommends disabling:
# wrong-import-order when using isort
# missing-module-docstring,missing-class-docstring,missing-function-docstring when using pydocstyle
disable = """
R,fixme,no-member,unsupported-membership-test,unsubscriptable-object,
unsupported-assignment-operation,not-an-iterable,too-many-lines,wrong-import-order,
missing-module-docstring,missing-class-docstring,missing-function-docstring
"""

[tool.pylint.reports]
score = false
